---

- hosts: k8s1
  become: True
  tasks:
    - name: Install docker daemon
      yum:
        name: docker
        state: present
    - name: Start and enable docker daemon
      service:
        name: docker
        state: started
        enabled: True

    - name: Create springboot
      docker_container: 
        name: springbootapi
        image: boot-api:1.1
         
        
